% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{lmodern}
\usepackage{amssymb,amsmath}
\usepackage{ifxetex,ifluatex}
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\hypersetup{
  pdftitle={Homework 3},
  pdfauthor={Ericka Smith},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}
\urlstyle{same} % disable monospaced font for URLs
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx,grffile}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering

\title{Homework 3}
\author{Ericka Smith}
\date{10/14/2020}

\begin{document}
\maketitle

\hypertarget{problem-1}{%
\subsection{Problem 1}\label{problem-1}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{dat <-}\StringTok{ }\KeywordTok{data.frame}\NormalTok{(}
  \DataTypeTok{x =} \KeywordTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{, }\FloatTok{0.5}\NormalTok{, }\DecValTok{1}\NormalTok{, }\DecValTok{2}\NormalTok{, }\DecValTok{3}\NormalTok{, }\DecValTok{4}\NormalTok{, }\DecValTok{5}\NormalTok{, }\DecValTok{5}\NormalTok{, }\FloatTok{5.5}\NormalTok{, }\DecValTok{6}\NormalTok{),}
  \DataTypeTok{y =} \KeywordTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{, }\DecValTok{0}\NormalTok{, }\DecValTok{0}\NormalTok{, }\DecValTok{0}\NormalTok{, }\DecValTok{0}\NormalTok{, }\DecValTok{1}\NormalTok{, }\DecValTok{1}\NormalTok{, }\DecValTok{1}\NormalTok{, }\DecValTok{1}\NormalTok{, }\DecValTok{1}\NormalTok{))}

\KeywordTok{ggplot}\NormalTok{(}\DataTypeTok{data =}\NormalTok{ dat, }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x =}\NormalTok{ x, }\DataTypeTok{y=}\NormalTok{y))}\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_point}\NormalTok{(}\DataTypeTok{size =} \DecValTok{2}\NormalTok{)}\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_smooth}\NormalTok{(}\DataTypeTok{method =} \StringTok{"glm"}\NormalTok{, }\DataTypeTok{method.args =} \KeywordTok{list}\NormalTok{(}\DataTypeTok{family=}\NormalTok{binomial), }\DataTypeTok{se=}\NormalTok{F)}\OperatorTok{+}
\StringTok{  }\KeywordTok{theme_light}\NormalTok{()}\OperatorTok{+}
\StringTok{  }\KeywordTok{ggtitle}\NormalTok{(}\StringTok{"HW3 Problem 1"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## `geom_smooth()` using formula 'y ~ x'
\end{verbatim}

\includegraphics{hw3_files/figure-latex/unnamed-chunk-1-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{summary}\NormalTok{(}\KeywordTok{glm}\NormalTok{(y}\OperatorTok{~}\NormalTok{x, }\DataTypeTok{family =}\NormalTok{ binomial, }\DataTypeTok{data=}\NormalTok{dat))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## glm(formula = y ~ x, family = binomial, data = dat)
## 
## Deviance Residuals: 
##        Min          1Q      Median          3Q         Max  
## -1.575e-05  -2.110e-08   0.000e+00   2.110e-08   1.607e-05  
## 
## Coefficients:
##              Estimate Std. Error z value Pr(>|z|)
## (Intercept)   -159.55  270391.50  -0.001        1
## x               45.58   76267.22   0.001        1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 1.3863e+01  on 9  degrees of freedom
## Residual deviance: 5.0616e-10  on 8  degrees of freedom
## AIC: 4
## 
## Number of Fisher Scoring iterations: 25
\end{verbatim}

For both the intercept and the coefficient for x we get p-values equal
to 1, so neither estimate is significant and we can't interpret their
values in a very meaningful way. That being said, in a logistic
regression output such as this the intercept signifies the log odds of
being in the \(p(x)=0\) group for y, and the coefficient of x signifies
the change in the log odds of being in the \(p(x)=1\) group as compared
to the \(p(x)=0\) group.

\hypertarget{problem-2}{%
\subsection{Problem 2}\label{problem-2}}

\hypertarget{part-a}{%
\paragraph{Part A}\label{part-a}}

They are equivalent as parameter points because the constant \(c\) falls
away in the model, because \(\alpha_i=log(w_i)\) and and \(+c\) is the
only difference between \(\alpha_1, ..., \alpha_8\) as compared to
\(\alpha_1+c, ..., \alpha_8+c\). We can still estimate the weights
\(w_1,...,w_8\) because we have the relationship between these already.

\hypertarget{part-b}{%
\paragraph{Part B}\label{part-b}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{X <-}\StringTok{ }\KeywordTok{read_csv}\NormalTok{(}\StringTok{"p2.csv"}\NormalTok{, }\DataTypeTok{col_names =} \OtherTok{FALSE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Parsed with column specification:
## cols(
##   X1 = col_double(),
##   X2 = col_double(),
##   X3 = col_double(),
##   X4 = col_double(),
##   X5 = col_double(),
##   X6 = col_double(),
##   X7 = col_double()
## )
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{(xmat <-}\StringTok{ }\KeywordTok{as.matrix}\NormalTok{(X))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##       X1 X2 X3 X4 X5 X6 X7
##  [1,]  1 -1  0  0  0  0  0
##  [2,]  1  0 -1  0  0  0  0
##  [3,]  1  0  0 -1  0  0  0
##  [4,]  1  0  0  0 -1  0  0
##  [5,]  1  0  0  0  0 -1  0
##  [6,]  1  0  0  0  0  0 -1
##  [7,]  1  0  0  0  0  0  0
##  [8,]  0  1 -1  0  0  0  0
##  [9,]  0  1  0 -1  0  0  0
## [10,]  0  1  0  0 -1  0  0
## [11,]  0  1  0  0  0 -1  0
## [12,]  0  1  0  0  0  0 -1
## [13,]  0  1  0  0  0  0  0
## [14,]  0  0  1 -1  0  0  0
## [15,]  0  0  1  0 -1  0  0
## [16,]  0  0  1  0  0 -1  0
## [17,]  0  0  1  0  0  0 -1
## [18,]  0  0  1  0  0  0  0
## [19,]  0  0  0  1 -1  0  0
## [20,]  0  0  0  1  0 -1  0
## [21,]  0  0  0  1  0  0 -1
## [22,]  0  0  0  1  0  0  0
## [23,]  0  0  0  0  1 -1  0
## [24,]  0  0  0  0  1  0 -1
## [25,]  0  0  0  0  1  0  0
## [26,]  0  0  0  0  0  1 -1
## [27,]  0  0  0  0  0  1  0
## [28,]  0  0  0  0  0  0  1
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{y <-}\StringTok{ }\KeywordTok{c}\NormalTok{(}\DecValTok{5}\NormalTok{,}\DecValTok{3}\NormalTok{,}\DecValTok{7}\NormalTok{,}\DecValTok{6}\NormalTok{,}\DecValTok{6}\NormalTok{,}\DecValTok{1}\OperatorTok{/}\DecValTok{3}\NormalTok{,}\DecValTok{1}\OperatorTok{/}\DecValTok{4}\NormalTok{,}\DecValTok{1}\OperatorTok{/}\DecValTok{3}\NormalTok{,}\DecValTok{5}\NormalTok{,}\DecValTok{3}\NormalTok{,}\DecValTok{3}\NormalTok{,}\DecValTok{1}\OperatorTok{/}\DecValTok{5}\NormalTok{,}\DecValTok{1}\OperatorTok{/}\DecValTok{7}\NormalTok{,}\DecValTok{6}\NormalTok{,}\DecValTok{3}\NormalTok{,}\DecValTok{4}\NormalTok{,}\DecValTok{6}\NormalTok{,}\DecValTok{1}\OperatorTok{/}\DecValTok{5}\NormalTok{,}\DecValTok{1}\OperatorTok{/}\DecValTok{3}\NormalTok{,}\DecValTok{1}\OperatorTok{/}\DecValTok{4}\NormalTok{,}\DecValTok{1}\OperatorTok{/}\DecValTok{7}\NormalTok{,}\DecValTok{1}\OperatorTok{/}\DecValTok{8}\NormalTok{,}\DecValTok{1}\OperatorTok{/}\DecValTok{2}\NormalTok{,}\DecValTok{1}\OperatorTok{/}\DecValTok{5}\NormalTok{,}\DecValTok{1}\OperatorTok{/}\DecValTok{6}\NormalTok{,}\DecValTok{1}\OperatorTok{/}\DecValTok{5}\NormalTok{,}\DecValTok{1}\OperatorTok{/}\DecValTok{6}\NormalTok{,}\DecValTok{1}\OperatorTok{/}\DecValTok{2}\NormalTok{)}
\NormalTok{logy <-}\StringTok{ }\KeywordTok{map_dbl}\NormalTok{(y, }\OperatorTok{~}\KeywordTok{log}\NormalTok{(.x))}
\NormalTok{model0 <-}\StringTok{ }\KeywordTok{lm}\NormalTok{(y}\OperatorTok{~}\NormalTok{xmat)}
\KeywordTok{summary}\NormalTok{(model0)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = y ~ xmat)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -2.7216 -0.7734  0.0876  0.7992  3.1946 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(>|t|)    
## (Intercept)   2.4300     0.5442   4.465 0.000237 ***
## xmatX1       -0.6107     1.1938  -0.512 0.614550    
## xmatX2       -2.6166     1.0884  -2.404 0.026020 *  
## xmatX3       -0.8603     0.9904  -0.869 0.395366    
## xmatX4       -4.3797     0.9024  -4.853 9.64e-05 ***
## xmatX5       -3.0619     0.8275  -3.700 0.001417 ** 
## xmatX6       -2.6940     0.7696  -3.501 0.002252 ** 
## xmatX7       -1.2356     0.7326  -1.687 0.107222    
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 1.44 on 20 degrees of freedom
## Multiple R-squared:  0.7459, Adjusted R-squared:  0.6569 
## F-statistic: 8.386 on 7 and 20 DF,  p-value: 8.272e-05
\end{verbatim}

Here are the estimates I obtain:

\(\alpha_1-\alpha_2 = -0.6107\)

\(\alpha_1-\alpha_3 = -2.6166\)

\(\alpha_1-\alpha_4 = -0.8603\)

\(\alpha_1-\alpha_5 = -4.3797\)

\(\alpha_1-\alpha_6 = -3.0619\)

\(\alpha_1-\alpha_7 = -2.6940\)

\(\alpha_1-\alpha_8 = -1.2356\)

\hypertarget{part-c}{%
\paragraph{Part C}\label{part-c}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{exp_a <-}\StringTok{ }\KeywordTok{unname}\NormalTok{(}\KeywordTok{exp}\NormalTok{(model0}\OperatorTok{$}\NormalTok{coefficients))}
\NormalTok{w <-}\StringTok{ }\KeywordTok{rbind}\NormalTok{(}\KeywordTok{diag}\NormalTok{(}\OperatorTok{-}\DecValTok{1}\NormalTok{,}\DecValTok{7}\NormalTok{,}\DecValTok{7}\NormalTok{), }\KeywordTok{rep}\NormalTok{(}\DecValTok{1}\NormalTok{,}\DecValTok{7}\NormalTok{))}
\NormalTok{(w <-}\StringTok{ }\KeywordTok{cbind}\NormalTok{(w, }\KeywordTok{as.vector}\NormalTok{(exp_a)))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##      [,1] [,2] [,3] [,4] [,5] [,6] [,7]        [,8]
## [1,]   -1    0    0    0    0    0    0 11.35907526
## [2,]    0   -1    0    0    0    0    0  0.54296290
## [3,]    0    0   -1    0    0    0    0  0.07305060
## [4,]    0    0    0   -1    0    0    0  0.42303976
## [5,]    0    0    0    0   -1    0    0  0.01252887
## [6,]    0    0    0    0    0   -1    0  0.04679648
## [7,]    0    0    0    0    0    0   -1  0.06760818
## [8,]    1    1    1    1    1    1    1  0.29065181
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{(z <-}\StringTok{ }\KeywordTok{c}\NormalTok{(}\KeywordTok{rep}\NormalTok{(}\DecValTok{0}\NormalTok{,}\DecValTok{7}\NormalTok{), }\DecValTok{1}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0 0 0 0 0 0 0 1
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{solve}\NormalTok{(w,z)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.8863396439 0.0423669649 0.0057000807 0.0330094571 0.0009776181
## [6] 0.0036514923 0.0052754124 0.0780292078
\end{verbatim}

The estimates of the weights are the following:

\(w_1 = 0.8863396439\)

\(w_2 = 0.0423669649\)

\(w_3 = 0.0057000807\)

\(w_4 = 0.0330094571\)

\(w_5 = 0.0009776181\)

\(w_6 = 0.0036514923\)

\(w_7 = 0.0052754124\)

\(w_8 = 0.0780292078\)

\hypertarget{part-d}{%
\paragraph{Part D}\label{part-d}}

Since only certain \(\alpha\) estimates were significant that calls into
question the hypothesis that all 8 criteria are equally important. The
varying magnitudes of the weights also do. For example, \(w_5\) is a LOT
smaller than the other weights, which leads me to believe that yard
space (5) is not actually as important as some of the other criteria.

\hypertarget{part-e}{%
\paragraph{Part E}\label{part-e}}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{plot}\NormalTok{(model0)}
\end{Highlighting}
\end{Shaded}

\includegraphics{hw3_files/figure-latex/unnamed-chunk-4-1.pdf}
\includegraphics{hw3_files/figure-latex/unnamed-chunk-4-2.pdf}
\includegraphics{hw3_files/figure-latex/unnamed-chunk-4-3.pdf}
\includegraphics{hw3_files/figure-latex/unnamed-chunk-4-4.pdf}

Based on the plots the model assumptions are not quite met. In the
Residuals vs.~Fitted plot you can see that there is nonconstant variance
and on the Q-Q plot there is a bit of tailing off at the upper right
hand corner of the plot.

\hypertarget{problem-3}{%
\subsection{Problem 3}\label{problem-3}}

\hypertarget{parts-a-and-b}{%
\paragraph{Parts A and B}\label{parts-a-and-b}}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# dat <- data.frame(}
\CommentTok{#   insecticide = c(2, 2.64, 3.48, 4.59, 6.06, 8),}
\CommentTok{#   ddt = c(3/50, 5/49, 19/47, 19/38, 24/49, 35/50),}
\CommentTok{#   bhc = c(2/50, 14/49, 20/50, 27/50, 41/50, 40/50),}
\CommentTok{#   both = c(28/50, 37/50, 46/50, 48/50, 48/50, 50/50))}
\NormalTok{df <-}\StringTok{ }\KeywordTok{data.frame}\NormalTok{(}
\NormalTok{  dose <-}\StringTok{ }\KeywordTok{c}\NormalTok{(}\DecValTok{2}\NormalTok{, }\FloatTok{2.64}\NormalTok{, }\FloatTok{3.48}\NormalTok{, }\FloatTok{4.59}\NormalTok{, }\FloatTok{6.06}\NormalTok{, }\DecValTok{8}\NormalTok{, }\DecValTok{2}\NormalTok{, }\FloatTok{2.64}\NormalTok{, }\FloatTok{3.48}\NormalTok{, }\FloatTok{4.59}\NormalTok{, }\FloatTok{6.06}\NormalTok{, }\DecValTok{8}\NormalTok{, }\DecValTok{2}\NormalTok{, }\FloatTok{2.64}\NormalTok{, }\FloatTok{3.48}\NormalTok{, }\FloatTok{4.59}\NormalTok{, }\FloatTok{6.06}\NormalTok{, }\DecValTok{8}\NormalTok{),}
\NormalTok{  kr <-}\StringTok{ }\KeywordTok{c}\NormalTok{(}\DecValTok{3}\OperatorTok{/}\DecValTok{50}\NormalTok{, }\DecValTok{5}\OperatorTok{/}\DecValTok{49}\NormalTok{, }\DecValTok{19}\OperatorTok{/}\DecValTok{47}\NormalTok{, }\DecValTok{19}\OperatorTok{/}\DecValTok{38}\NormalTok{, }\DecValTok{24}\OperatorTok{/}\DecValTok{49}\NormalTok{, }\DecValTok{35}\OperatorTok{/}\DecValTok{50}\NormalTok{, }\DecValTok{2}\OperatorTok{/}\DecValTok{50}\NormalTok{, }\DecValTok{14}\OperatorTok{/}\DecValTok{49}\NormalTok{, }\DecValTok{20}\OperatorTok{/}\DecValTok{50}\NormalTok{, }\DecValTok{27}\OperatorTok{/}\DecValTok{50}\NormalTok{, }\DecValTok{41}\OperatorTok{/}\DecValTok{50}\NormalTok{, }\DecValTok{40}\OperatorTok{/}\DecValTok{50}\NormalTok{, }\DecValTok{28}\OperatorTok{/}\DecValTok{50}\NormalTok{, }\DecValTok{37}\OperatorTok{/}\DecValTok{50}\NormalTok{, }\DecValTok{46}\OperatorTok{/}\DecValTok{50}\NormalTok{, }\DecValTok{48}\OperatorTok{/}\DecValTok{50}\NormalTok{, }\DecValTok{48}\OperatorTok{/}\DecValTok{50}\NormalTok{, }\DecValTok{50}\OperatorTok{/}\DecValTok{50}\NormalTok{),}
\NormalTok{  insecticide <-}\StringTok{ }\KeywordTok{c}\NormalTok{(}\StringTok{"DDT"}\NormalTok{, }\StringTok{"DDT"}\NormalTok{, }\StringTok{"DDT"}\NormalTok{, }\StringTok{"DDT"}\NormalTok{, }\StringTok{"DDT"}\NormalTok{, }\StringTok{"DDT"}\NormalTok{, }\StringTok{"BHC"}\NormalTok{, }\StringTok{"BHC"}\NormalTok{, }\StringTok{"BHC"}\NormalTok{, }\StringTok{"BHC"}\NormalTok{, }\StringTok{"BHC"}\NormalTok{, }\StringTok{"BHC"}\NormalTok{, }\StringTok{"BOTH"}\NormalTok{, }\StringTok{"BOTH"}\NormalTok{, }\StringTok{"BOTH"}\NormalTok{, }\StringTok{"BOTH"}\NormalTok{, }\StringTok{"BOTH"}\NormalTok{, }\StringTok{"BOTH"}\NormalTok{))}

\KeywordTok{ggplot}\NormalTok{(}\DataTypeTok{data =}\NormalTok{ df)}\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_smooth}\NormalTok{(}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x =}\NormalTok{ dose, }\DataTypeTok{y=}\NormalTok{kr, }\DataTypeTok{color=}\NormalTok{insecticide), }\DataTypeTok{method =} \StringTok{"glm"}\NormalTok{, }\DataTypeTok{method.args =} \KeywordTok{list}\NormalTok{(}\DataTypeTok{family=}\NormalTok{binomial), }\DataTypeTok{se=}\NormalTok{F)}\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_point}\NormalTok{(}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x =}\NormalTok{ dose, }\DataTypeTok{y=}\NormalTok{kr, }\DataTypeTok{color=}\NormalTok{insecticide))}\OperatorTok{+}
\StringTok{  }\KeywordTok{theme_light}\NormalTok{()}\OperatorTok{+}
\StringTok{  }\KeywordTok{ggtitle}\NormalTok{(}\StringTok{"Toxicity of Insecticides"}\NormalTok{)}\OperatorTok{+}
\StringTok{  }\KeywordTok{xlab}\NormalTok{(}\KeywordTok{as.expression}\NormalTok{(}\KeywordTok{bquote}\NormalTok{(}\StringTok{"Insecticide Dose (mg/10"} \OperatorTok{~}\StringTok{ }\NormalTok{cm}\OperatorTok{^}\DecValTok{2} \OperatorTok{~}\StringTok{ ")"}\NormalTok{)))}\OperatorTok{+}
\StringTok{  }\KeywordTok{ylab}\NormalTok{(}\StringTok{"Kill Rate"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## `geom_smooth()` using formula 'y ~ x'
\end{verbatim}

\begin{verbatim}
## Warning in eval(family$initialize): non-integer #successes in a binomial glm!

## Warning in eval(family$initialize): non-integer #successes in a binomial glm!

## Warning in eval(family$initialize): non-integer #successes in a binomial glm!
\end{verbatim}

\includegraphics{hw3_files/figure-latex/unnamed-chunk-5-1.pdf}

\hypertarget{part-c-1}{%
\paragraph{Part C}\label{part-c-1}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{mod <-}\StringTok{ }\KeywordTok{glm}\NormalTok{(kr }\OperatorTok{~}\StringTok{ }\KeywordTok{log}\NormalTok{(dose) }\OperatorTok{+}\StringTok{ }\NormalTok{insecticide, }\DataTypeTok{family=}\StringTok{"binomial"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning in eval(family$initialize): non-integer #successes in a binomial glm!
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{ggplot}\NormalTok{(mod)}\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_smooth}\NormalTok{(}\KeywordTok{aes}\NormalTok{(}\KeywordTok{log}\NormalTok{(dose), .fitted, }\DataTypeTok{color =}\NormalTok{ insecticide), }\DataTypeTok{se =}\NormalTok{ F)}\OperatorTok{+}
\StringTok{  }\KeywordTok{theme_light}\NormalTok{()}\OperatorTok{+}
\StringTok{  }\KeywordTok{ggtitle}\NormalTok{(}\StringTok{"log(dose) vs. fitted"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## `geom_smooth()` using method = 'loess' and formula 'y ~ x'
\end{verbatim}

\includegraphics{hw3_files/figure-latex/unnamed-chunk-6-1.pdf}

Looking at the plot of log(dose) vs.~fitted values we see that these
lines are parallel. This gives evidence to the hypothesis of
parallelism.

\hypertarget{part-d-1}{%
\paragraph{Part D}\label{part-d-1}}

In the formula chem+ldose there is an intercept term and in the formula
chem+ldose-1 there is not. Since this is the only difference the
covariance matrices will be the same.

\hypertarget{part-e-1}{%
\paragraph{Part E}\label{part-e-1}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{a =}\StringTok{ }\NormalTok{mod}\OperatorTok{$}\NormalTok{coefficients[}\DecValTok{1}\NormalTok{]    }
\NormalTok{b =}\StringTok{ }\NormalTok{mod}\OperatorTok{$}\NormalTok{coefficients[}\DecValTok{2}\NormalTok{]}
\NormalTok{V=}\KeywordTok{vcov}\NormalTok{(mod)}
\NormalTok{z =}\StringTok{ }\FloatTok{1.645}\NormalTok{;}
\NormalTok{k =}\StringTok{ }\FloatTok{1.645}\OperatorTok{^}\DecValTok{2}\OperatorTok{*}\NormalTok{V[}\DecValTok{2}\NormalTok{,}\DecValTok{2}\NormalTok{]}\OperatorTok{/}\NormalTok{b}\OperatorTok{^}\DecValTok{2}
\NormalTok{(}\DataTypeTok{tau =} \KeywordTok{polyroot}\NormalTok{(}\KeywordTok{c}\NormalTok{(a}\OperatorTok{^}\DecValTok{2} \OperatorTok{-}\StringTok{ }\NormalTok{V[}\DecValTok{1}\NormalTok{,}\DecValTok{1}\NormalTok{]}\OperatorTok{*}\NormalTok{z}\OperatorTok{*}\NormalTok{z,}\DecValTok{2}\OperatorTok{*}\NormalTok{a}\OperatorTok{*}\NormalTok{b }\OperatorTok{-}\StringTok{ }\DecValTok{2}\OperatorTok{*}\NormalTok{V[}\DecValTok{1}\NormalTok{,}\DecValTok{2}\NormalTok{]}\OperatorTok{*}\NormalTok{z}\OperatorTok{*}\NormalTok{z,b}\OperatorTok{^}\DecValTok{2} \OperatorTok{-}\StringTok{ }\NormalTok{V[}\DecValTok{2}\NormalTok{,}\DecValTok{2}\NormalTok{]}\OperatorTok{*}\NormalTok{z}\OperatorTok{*}\NormalTok{z)))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] -0.0048049+0i  3.0788096+0i
\end{verbatim}

The 90\% Confidence Interval that I obtain is (-0.0048049, 3.0788096)

\hypertarget{part-f}{%
\paragraph{Part F}\label{part-f}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{mod_probit <-}\StringTok{ }\KeywordTok{glm}\NormalTok{(kr }\OperatorTok{~}\StringTok{ }\KeywordTok{log}\NormalTok{(dose) }\OperatorTok{+}\StringTok{ }\NormalTok{insecticide, }\DataTypeTok{family=}\KeywordTok{binomial}\NormalTok{(}\DataTypeTok{link =} \StringTok{"probit"}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning in eval(family$initialize): non-integer #successes in a binomial glm!
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{mod_cloglog <-}\StringTok{ }\KeywordTok{glm}\NormalTok{(kr }\OperatorTok{~}\StringTok{ }\KeywordTok{log}\NormalTok{(dose) }\OperatorTok{+}\StringTok{ }\NormalTok{insecticide, }\DataTypeTok{family=}\KeywordTok{binomial}\NormalTok{(}\DataTypeTok{link =} \StringTok{"cloglog"}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning in eval(family$initialize): non-integer #successes in a binomial glm!
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{mod_loglog <-}\StringTok{ }\KeywordTok{glm}\NormalTok{((}\DecValTok{1}\OperatorTok{-}\NormalTok{kr) }\OperatorTok{~}\StringTok{ }\KeywordTok{log}\NormalTok{(dose) }\OperatorTok{+}\StringTok{ }\NormalTok{insecticide, }\DataTypeTok{family=}\KeywordTok{binomial}\NormalTok{(}\DataTypeTok{link=}\StringTok{"cloglog"}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning in eval(family$initialize): non-integer #successes in a binomial glm!
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{ggplot}\NormalTok{(mod_probit)}\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_smooth}\NormalTok{(}\KeywordTok{aes}\NormalTok{(}\KeywordTok{log}\NormalTok{(dose), .fitted, }\DataTypeTok{color =}\NormalTok{ insecticide), }\DataTypeTok{se =}\NormalTok{ F)}\OperatorTok{+}
\StringTok{  }\KeywordTok{theme_light}\NormalTok{()}\OperatorTok{+}
\StringTok{  }\KeywordTok{ggtitle}\NormalTok{(}\StringTok{"probit model"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## `geom_smooth()` using method = 'loess' and formula 'y ~ x'
\end{verbatim}

\includegraphics{hw3_files/figure-latex/unnamed-chunk-8-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{ggplot}\NormalTok{(mod_cloglog)}\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_smooth}\NormalTok{(}\KeywordTok{aes}\NormalTok{(}\KeywordTok{log}\NormalTok{(dose), .fitted, }\DataTypeTok{color =}\NormalTok{ insecticide), }\DataTypeTok{se =}\NormalTok{ F)}\OperatorTok{+}
\StringTok{  }\KeywordTok{theme_light}\NormalTok{()}\OperatorTok{+}
\StringTok{  }\KeywordTok{ggtitle}\NormalTok{(}\StringTok{"c-log-log model"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## `geom_smooth()` using method = 'loess' and formula 'y ~ x'
\end{verbatim}

\includegraphics{hw3_files/figure-latex/unnamed-chunk-8-2.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{ggplot}\NormalTok{(mod_loglog)}\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_smooth}\NormalTok{(}\KeywordTok{aes}\NormalTok{(}\KeywordTok{log}\NormalTok{(dose), .fitted, }\DataTypeTok{color =}\NormalTok{ insecticide), }\DataTypeTok{se =}\NormalTok{ F)}\OperatorTok{+}
\StringTok{  }\KeywordTok{theme_light}\NormalTok{()}\OperatorTok{+}
\StringTok{  }\KeywordTok{ggtitle}\NormalTok{(}\StringTok{"log-log model"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## `geom_smooth()` using method = 'loess' and formula 'y ~ x'
\end{verbatim}

\includegraphics{hw3_files/figure-latex/unnamed-chunk-8-3.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{a =}\StringTok{ }\NormalTok{mod_cloglog}\OperatorTok{$}\NormalTok{coefficients[}\DecValTok{1}\NormalTok{]    }
\NormalTok{b =}\StringTok{ }\NormalTok{mod_cloglog}\OperatorTok{$}\NormalTok{coefficients[}\DecValTok{2}\NormalTok{]}
\NormalTok{V=}\KeywordTok{vcov}\NormalTok{(mod_cloglog)}
\NormalTok{z =}\StringTok{ }\FloatTok{1.645}\NormalTok{;}
\NormalTok{k =}\StringTok{ }\FloatTok{1.645}\OperatorTok{^}\DecValTok{2}\OperatorTok{*}\NormalTok{V[}\DecValTok{2}\NormalTok{,}\DecValTok{2}\NormalTok{]}\OperatorTok{/}\NormalTok{b}\OperatorTok{^}\DecValTok{2}
\NormalTok{(}\DataTypeTok{tau =} \KeywordTok{polyroot}\NormalTok{(}\KeywordTok{c}\NormalTok{(a}\OperatorTok{^}\DecValTok{2} \OperatorTok{-}\StringTok{ }\NormalTok{V[}\DecValTok{1}\NormalTok{,}\DecValTok{1}\NormalTok{]}\OperatorTok{*}\NormalTok{z}\OperatorTok{*}\NormalTok{z,}\DecValTok{2}\OperatorTok{*}\NormalTok{a}\OperatorTok{*}\NormalTok{b }\OperatorTok{-}\StringTok{ }\DecValTok{2}\OperatorTok{*}\NormalTok{V[}\DecValTok{1}\NormalTok{,}\DecValTok{2}\NormalTok{]}\OperatorTok{*}\NormalTok{z}\OperatorTok{*}\NormalTok{z,b}\OperatorTok{^}\DecValTok{2} \OperatorTok{-}\StringTok{ }\NormalTok{V[}\DecValTok{2}\NormalTok{,}\DecValTok{2}\NormalTok{]}\OperatorTok{*}\NormalTok{z}\OperatorTok{*}\NormalTok{z)))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.532220-0i 4.451669+0i
\end{verbatim}

It really doesn't seem to me that any of them gives an appreciably
better fit. For my 90\% confidence interval for the c-log-log model I
get (0.532220,4.451669).

\hypertarget{part-g}{%
\paragraph{Part G}\label{part-g}}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{predict}\NormalTok{(mod, }\DataTypeTok{type =} \StringTok{"response"}\NormalTok{)[}\DecValTok{18}\NormalTok{]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##        18 
## 0.9848035
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{exp}\NormalTok{(}\KeywordTok{predict}\NormalTok{(mod)[}\DecValTok{18}\NormalTok{])}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##       18 
## 64.80447
\end{verbatim}

The closest we can reliably get to 0.99 is 0.98480346, and this occurs
at a dose of \(64.8 mg/10cm^2\)

\hypertarget{part-h}{%
\paragraph{Part H}\label{part-h}}

It seems pretty clear to me based upon the prior plots and models that
both insecticides together are the most effective. DDT appears to be
less effective than gamma-BHC but the two are fairly similar overall.

\end{document}
